---
language: python
python: "2.7"

os:
  - linux

install:
  # Install Ansible.
  - pip install ansible

script:
  # Check the role/playbook's syntax.
  - "ansible-playbook -i inventory disk.yml --syntax-check"
  - "ansible-playbook -i inventory disk.yml"
