---
language: python
python: "2.7"

env:
  - SITE=disk.yml

install:
  # Install Ansible.
  - pip install ansible

script:
  # Check the role/playbook's syntax.
  - "ansible-playbook disk.yml --syntax-check"
